### PR TITLE
Newsweek project

### PR DESCRIPTION
**Pull request by phylischumba**
This is a bootstrap project. I have created various sections using basically bootstrap classes and less CSS. 
It has the navbar, the body, and the footer

### CODE REVIEW

**Comment by uryelah** [comment]
Hello **Phylis Chepchumba**, I'm Sarah, your reviewer for this PR 👩‍🚀  

**First of all, you did a really great job with this project.🎇**
I especially liked your editor's picks and featured slideshows sections.
You also worked really well with the responsive bootstrap columns. 

There are still some issues to work through so hang in there 💪 

---------    

### Required changes 🛠 
---------

- [x]  Remember to use Semantic HTML for the site sections and articles. [Read more here.](https://bitsofco.de/sectioning-content-in-html5/)

- [ ] Since a lot of the responsiveness and style are being handled by Bootstrap this project needs to be as close as possible to the original site. This includes **attention to font style**, **color** and **spacing**. Compare your clone and [the original site ](https://www.newsweek.com/
Screenshot_2020-03-20 Microverse Main Curriculum
)carefully and find the differences in style so they can get fixed.

- [x] The navbar and footer logo should be exactly the same as used in the Newsweek site, not just the text. Try using an svg like they do in the original site or a similar font family.
**Your logo**
Screenshot_2020-03-20 Newsweek(11)
**Original logo**
Screenshot_2020-03-20 Newsweek(12)

- [x] Compare the two images above, the shade of red you are using is not close enough to the original red. It's ok to use regular CSS to change that. Tip: [Use a color picker.](https://developer.mozilla.org/en-US/docs/Tools/Eyedropper)

- [ ] The navigation bar in the original site is fixed to the top of the page. It always shows up even when you scroll down.
**Use Bootstrap to change your navbar position to fixed too.**

- [ ] Make sure your **Subscribe** and **Newsletter** sections align themselves vertically in small screens like in the original site. Compare your version bellow with the original one:
Screenshot_2020-03-20 Newsweek(9)
**Original site:**
Screenshot_2020-03-20 Newsweek(10)

- [x] The Featured Slideshows section in medium and big screens should have it's articles aligned horizontally. Compare your version and the original one:
Screenshot_2020-03-20 Newsweek(7)
**Original site**
Screenshot_2020-03-20 Newsweek(8)
------

- [x] The sections above **In the Magazine** are all aligned at the bottom. In your version only **More Stories** is longer. Compare your version and the original bellow. 
(Tip: try using  _overflow_ and _scroll_ to make them align).
Screenshot_2020-03-20 Newsweek(6)
**Original page:**
Screenshot_2020-03-20 Newsweek(5)
-------

- [x] Make sure your **Culture & Travel** section text for each article are also aligned at the bottom like the original. Compare your version and the original below:
Screenshot_2020-03-20 Newsweek(4)
**Original:**
Screenshot_2020-03-20 Newsweek(3)

---

- [x] Make sure there is a margin between the **Culture & Travel** articles. Use boostrap to add margin when desired. Compare your version and the original below:
Screenshot_2020-03-20 Newsweek(2)
**Original**
Screenshot_2020-03-20 Newsweek(1)

- [x] The images at **Top Story** and **Opinion** are getting distorted on screen resize.
Make sure that the Top image resizes keeping its proportion and that that the opinion author pics have a fixed size.
Screenshot_2020-03-20 Newsweek


--------

**Kindly fix the REQUIRED issues and send another code review request.**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello Team!
### Good work and for also making changes from previous reviews :clap: However, you have a few more issues to implement before your application can be approved.
- Concentrate more on the responsiveness of the application on mobile and medium screen sizes to fix a few issues highlighted below
medium columns
medium screen
menu mobile
menu on medium screen
mobile device 2
mobile device
#### Make all these changes and resubmit for another code review. Good luck.
- Contact me on slack @iamraymond for any clarification
- Happy coding!

**Comment by uryelah** [comment]
Hey, Phylis, you did a great job. Your clone has improved immensely since the first review!

That being said there are still some remaining issues on medium-small to small pages. 

---------    

### Required changes 🛠 
---------
- [x] The footer background color is clashing with the logo background color. Fix it so they are the same.
Screenshot_2020-03-23 Newsweek(3)

-----

- [x] At small screens your footer is not behaving the expected way. Compare your footer and the original one bellow:

Screenshot_2020-03-23 Newsweek(5)
**Original footer:**
Screenshot_2020-03-23 Newsweek(4)

----

- [x] Some of your images and text are bleeding out of the page on small screens. Check the screencaps bellow and make it so they are always contained in the page content:

Screenshot_2020-03-23 Newsweek(6)
Screenshot_2020-03-23 Newsweek


--------

### Optional Improvements

- [x] [OPTIONAL] The original page, as most pages, uses `svg` for the log instead of a normal image. Check it out how it's done in the [original page](https://www.newsweek.com/) and try to implement it in yours. The great thing about svgs is that it never loses definition, regardless of how big you need it to be.
[There's a good article about it on CSS tricks.](https://css-tricks.com/using-svg/)
--------

**Kindly fix the REQUIRED issues and send another code review request.**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes ♻️ 🚥 

Hi @Phylis05, you have done a great job 👍 The project is almost there before we can approve the project, we have to fix the comment by @uryelah. She made mention of  Images and text are bleeding out of the page. The problem still exists. Kindly fix it and send another code review. The image below shows what I currently have 
qf


Kindly make this change and submit another code review 😄 
_Happy coding_ 👩‍💻 
Daniel Larbi Addo

**Review by addod19 — APPROVED** [review]
## Status: Approved 🏆 🎈 

Hi @Phylis05, you did all the changes recommended by previous TSE's 👍 On this note, I hereby approve of your project ⭐️ See you at the top 🎖 Go ahead and merge to master and submit project completion form.

Good luck with your next projects 😄 
_Happy coding_ 👩‍💻 
Daniel Larbi Addo

**Pull request merged**
